# Generated by Django 5.2.2 on 2025-06-26 10:52

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3), users.validators.LettersDigitsSpacesUnderscoreValidator()])),
                ('password', models.CharField(help_text='Password length requirements: 8 to 20 characters', max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
